sudo: required
services:
  - docker
  
before_install:
  - docker build -t sanjeevthakur/react-test -f ./client/Dockerfile.dev ./client

script:
#-  docker run sanjeevthakur/react-test npm test -- --coverage
  - docker run -e CI=true sanjeevthakur/react-test npm test

after_success:
  - docker build -t sanjeevthakur/multi-client ./client
  - docker build -t sanjeevthakur/multi-nginx ./nginx
  - docker build -t sanjeevthakur/multi-server ./server
  - docker build -t sanjeevthakur/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sanjeevthakur/multi-client
  - docker push sanjeevthakur/multi-nginx
  - docker push sanjeevthakur/multi-server
  - docker push sanjeevthakur/multi-worker


  deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-162142872384
    bucket_path: docker-multi
    on:
      branch: master
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
